version: "3.4"

services:
  project:
    build: project
    image: project
    restart: "no"
    volumes:
      - ./project/:/app
    ports:
      - 7777:7777
    depends_on:
      - database
      - flyway
    env_file:
      - project.env

  database:
    container_name: database-p2-85e1a64b-f7e6-492b-983a-c14c29aea67b
    image: postgres:14.1
    restart: "no"
    env_file:
        - project.env

  flyway:
    image: flyway/flyway:8.4.0-alpine
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

  e2e-playwright:
    entrypoint: "/bin/true" # Prevent startup on docker-compose up
    build: e2e-playwright
    image: e2e-playwright
    network_mode: host
    depends_on:
      - project
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests